katharsis:
  resourcePackage: com.example.demo
  domainName: http://localhost:9090/shahwaghrayaccts
  pathPrefix: /

server:
  context-path: /shahwaghrayaccts
  port: 9090
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AccountLoginData
    username: root
    password: NewPassword 
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    hibernate:  
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
        hibernate:
          format_sql: true
          SQL: DEBUG
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id: 
          new_generator_mappings: false
        type: 
          descriptor:
            sql: 
              BasicBinder: TRACE
              
              